// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedisAuth } from "./RedisAuth";

export interface Database { id: string, name: string, comment: string, color: string, host: string, port: number, auth: RedisAuth, db: number, }