// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DatabaseDto { host: string, port: number, alias: string, db: number, username: string, password: string, tls: boolean, }