// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RedisAuth = "None" | PasswordAuth;

export interface PasswordAuth { username: string, password: string, }
